[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.10.11",
    "discord-py>=2.5.2",
    "flask>=3.0.3",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "yt-dlp>=2024.10.22",
]
